apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-this-guy
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: eggmart/test-app
        ports:
        - containerPort: 5000
