apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: test-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
      protocol: TCP